# Generated by Django 4.1.7 on 2023-03-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(default='default_pic.jpg', upload_to=''),
        ),
    ]
