# Generated by Django 4.1.7 on 2023-04-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
