# Generated by Django 4.1.7 on 2023-03-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='discription',
            new_name='description',
        ),
    ]
