# Generated by Django 4.1.7 on 2023-03-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='book_id',
            new_name='book_name',
        ),
    ]
