# Generated by Django 4.1.7 on 2023-03-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_title_alter_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='default_book.jpg', upload_to=''),
        ),
    ]
