# Generated by Django 4.1.7 on 2023-03-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='default_book.jpg', upload_to='books/'),
        ),
    ]
