# Generated by Django 4.1.7 on 2023-03-30 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_slug_alter_book_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
