# Generated by Django 4.1.7 on 2023-04-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_author_author_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='email',
            new_name='social_network',
        ),
        migrations.AddField(
            model_name='author',
            name='member_since',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
