# Generated by Django 4.1.7 on 2023-04-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_rename_email_author_social_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='social_network',
            field=models.CharField(max_length=100),
        ),
    ]
